apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: quay.io/srcmaxim/gradle-example-app:latest
          env:
            - name: SERVER_ADDRESS
              value: 0.0.0.0 # For http probes
          name: app
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /cat
              port: http
            periodSeconds: 45
          readinessProbe:
            httpGet:
              path: /cat
              port: http
            periodSeconds: 45
